# Tensors

Python lists or tuples of numbers are collections of Python objects that are **individually allocated in memory**. PyTorch **tensors** or NumPy arrays, on the other hand, are views over (typically) **contiguous memory blocks** containing unboxed C numeric types rather than Python objects.

In [36]:
import torch
import numpy as np

## Create Tensors

One-dimensional tensors (1D):

In [3]:
my_tensor = torch.ones(10)
print(my_tensor)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [4]:
my_tensor = torch.zeros(10)
print(my_tensor)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [5]:
my_tensor = torch.tensor([1.0, 4.0, 6.1])
print(my_tensor)

tensor([1.0000, 4.0000, 6.1000])


Two-dimensional tensors (2D):

In [9]:
my_tensor = torch.ones(2, 2)
print(my_tensor)

tensor([[1., 1.],
        [1., 1.]])


In [10]:
my_tensor = torch.tensor([[1.0, 4.0], [6.1, 2.0], [1.1, 2.1]])
print(my_tensor)

tensor([[1.0000, 4.0000],
        [6.1000, 2.0000],
        [1.1000, 2.1000]])


In [40]:
np_tensor = np.random.randn(3, 2)
my_tensor = torch.from_numpy(np_tensor)
my_tensor

tensor([[-0.3077, -0.2012],
        [-0.4857,  0.2088],
        [ 0.3434, -0.8606]], dtype=torch.float64)

In [42]:
np_tensor_converted = my_tensor.numpy()
np_tensor_converted

array([[-0.30770746, -0.20119509],
       [-0.48573912,  0.20875854],
       [ 0.34335148, -0.86063035]])

**Shape**: size of the tensor along each dimension

In [11]:
my_tensor.shape

torch.Size([3, 2])

## Tensor operations

In [14]:
img_t = torch.randn(3, 5, 5) # shape [(RGB)channels, rows, columns]
print(img_t.shape)

torch.Size([3, 5, 5])


In [16]:
weights = torch.tensor([0.22, 0.11, 0.05])
print(weights.shape)

torch.Size([3])


In [17]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, (RGB)channels, rows, columns]
print(batch_t.shape)

torch.Size([2, 3, 5, 5])


In [20]:
img_gray_naive = img_t.mean(-3) # RGB always at position -3
batch_gray_naive = batch_t.mean(-3) # RGB always at position -3

img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

Multiply tensor of shape (2, 3, 5, 5) by a tensorof shape (3)
- Unsqueeze (3) $\rightarrow$ (3, 1, 1)
- Multiply (exploiting broadcasting) 

In [23]:
print(weights.shape)
weights

torch.Size([3])


tensor([0.2200, 0.1100, 0.0500])

In [22]:
weights.unsqueeze(-1)

tensor([[0.2200],
        [0.1100],
        [0.0500]])

In [24]:
weights.unsqueeze(-1).unsqueeze(-1)

tensor([[[0.2200]],

        [[0.1100]],

        [[0.0500]]])

In [25]:
weights.unsqueeze(-1).unsqueeze(-1).shape

torch.Size([3, 1, 1])

In [26]:
img_t.shape

torch.Size([3, 5, 5])

In [27]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
img_weights = (img_t * unsqueezed_weights)

In [29]:
img_weights.shape

torch.Size([3, 5, 5])

In [30]:
batch_weights = (batch_t * unsqueezed_weights)
batch_weights.shape

torch.Size([2, 3, 5, 5])

## Tensors names

Create a tensor with name

In [31]:
weights_named = torch.tensor([1.0, 1.1, 1.2], names=['channels'])
weights_named

/var/folders/ck/5bn3d96976q9mdgwzsdcxtmw0000gn/T/ipykernel_6221/2881162734.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/c10/core/TensorImpl.h:1911.)
  weights_named = torch.tensor([1.0, 1.1, 1.2], names=['channels'])


tensor([1.0000, 1.1000, 1.2000], names=('channels',))

## Tensor datatypes
It is possible to specify the datatype in the constructor or cast the tensor.

In [32]:
double_t = torch.ones(3, 2, dtype=torch.double)
double_t

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [34]:
short_t = double_t.short()
short_t

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [35]:
double_t = torch.ones(3, 2).double()
double_t

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)